name: "OpenVPN client"
description: "Home Assistant OpenVPN client add-on"
version: "1.1.0"
slug: "openvpn_client"
init: false
advanced: true
startup: "application"
boot: "auto"
privileged:
  - "NET_ADMIN"
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  ovpn_config: ""
schema:
  ovpn_config: str
